# Generated by Django 2.1 on 2018-10-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='douban_top250',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('movie_name', models.CharField(max_length=255)),
                ('introduce', models.CharField(max_length=255)),
                ('star', models.FloatField(max_length=12)),
                ('evaluate', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
